"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { AuthContext } from "./context/auth-context/useAuthContext";
import { useState } from "react";
import Nav from "./Nav";
import { Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode;
  session: Session;
}) {
  const [authUser, setAuthUser] = useState<SessionUser | null>(null);

  // useEffect(() => {
  //   console.log({ authUser });
  // }, [authUser?.accessToken]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <AuthContext.Provider value={{ authUser, setAuthUser }}>
            <Nav />
            {children}
          </AuthContext.Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
